create table public.scan_requests (
  id bigint generated by default as identity not null,
  session_id text null,
  status text null default 'pending'::text,
  nfc_uid text null,
  response jsonb null,
  created_at timestamp with time zone null default now(),
  constraint scan_requests_pkey primary key (id)
) TABLESPACE pg_default;